import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsIn, IsInt, IsNotEmpty, IsOptional, IsString, Max, MaxLength, Min } from 'class-validator';

export const SUPPORT_BUNDLE_REFERENCE_TARGET_TYPES = ['issue_report', 'receipt'] as const;
export type SupportBundleReferenceTargetType =
  (typeof SUPPORT_BUNDLE_REFERENCE_TARGET_TYPES)[number];

export class CreateSupportBundleReferenceDto {
  @ApiProperty({
    example: 'bundle_9f8c1e2a4b3d',
    description: 'Identifier of the support bundle generated by the diagnostics endpoint',
  })
  @IsString()
  @IsNotEmpty()
  @MaxLength(128)
  bundleId!: string;

  @ApiProperty({ enum: SUPPORT_BUNDLE_REFERENCE_TARGET_TYPES })
  @IsIn(SUPPORT_BUNDLE_REFERENCE_TARGET_TYPES)
  targetType!: SupportBundleReferenceTargetType;

  @ApiProperty({ example: 'rcpt_abc123_0', description: 'Issue report id or receipt id to attach the bundle to' })
  @IsString()
  @IsNotEmpty()
  @MaxLength(256)
  targetId!: string;

  @ApiPropertyOptional({
    example: 30,
    description: 'Days until the reference expires and is redacted. Default 30, max 90.',
  })
  @IsOptional()
  @IsInt()
  @Min(1)
  @Max(90)
  ttlDays?: number;
}

export class ListSupportBundleReferencesQueryDto {
  @ApiProperty({ enum: SUPPORT_BUNDLE_REFERENCE_TARGET_TYPES })
  @IsIn(SUPPORT_BUNDLE_REFERENCE_TARGET_TYPES)
  targetType!: SupportBundleReferenceTargetType;

  @ApiProperty({ example: 'rcpt_abc123_0' })
  @IsString()
  @IsNotEmpty()
  targetId!: string;
}

export class SupportBundleReferenceResponseDto {
  @ApiProperty({ example: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890' })
  id!: string;

  @ApiProperty({
    example: 'bund****3d4b',
    description: 'Redacted bundle id — the raw value is never returned by lookups',
  })
  bundleIdMasked!: string;

  @ApiProperty({ enum: SUPPORT_BUNDLE_REFERENCE_TARGET_TYPES })
  targetType!: SupportBundleReferenceTargetType;

  @ApiProperty({ example: 'rcpt_abc123_0' })
  targetId!: string;

  @ApiProperty({ example: '2026-07-27T12:00:00.000Z' })
  createdAt!: string;

  @ApiProperty({ example: '2026-08-26T12:00:00.000Z' })
  expiresAt!: string;

  @ApiProperty({ example: false, description: 'Whether the reference has been redacted (expired or manually revoked)' })
  redacted!: boolean;
}
